######################################################################
# Automatically generated by qmake (3.0) Fri Feb 17 18:07:32 2017
######################################################################

TEMPLATE = app
TARGET = Future
INCLUDEPATH += .

QT += widgets concurrent

# Input
HEADERS += MyClass.h MyDlg.h
SOURCES += main.cpp MyClass.cpp MyDlg.cpp
