######################################################################
# Automatically generated by qmake (3.0) Fri Feb 17 14:52:30 2017
######################################################################

TEMPLATE = app
TARGET = WebView
INCLUDEPATH += .

QT += widgets webkitwidgets 

# Input
HEADERS += MyDlg.h
SOURCES += MyDlg.cpp
