######################################################################
# Automatically generated by qmake (3.0) Fri Feb 17 10:41:43 2017
######################################################################

TEMPLATE = app
TARGET = Checkbox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
