######################################################################
# Automatically generated by qmake (3.0) Fri Feb 17 19:14:41 2017
######################################################################

TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += Calculator.h
SOURCES += Calculator.cpp main.cpp
