######################################################################
# Automatically generated by qmake (3.0) Fri Feb 17 12:03:45 2017
######################################################################

TEMPLATE = app
TARGET = Server
INCLUDEPATH += .

QT += dbus

# Input
HEADERS += Chat.h ChatAdaptor.h ChatInterface.h
SOURCES += Chat.cpp ChatAdaptor.cpp ChatInterface.cpp main.cpp
